version: 2
updates:
  - directory: /
    package-ecosystem: "cargo"
    schedule:
      interval: "weekly"

  - directory: "/"
    package-ecosystem: "github-actions"
    schedule:
      interval: "weekly"
